const mongoose = require('mongoose');
require('dotenv').config();
const connectDB = require('./db');
const Car = require('./models/Car');
const Counter = require('./models/Counter');
const User = require('./models/User');

// Credentials are read from server/.env — never hardcode secrets in source.
const ADMIN_EMAIL = process.env.SEED_ADMIN_EMAIL || 'admin@yechalegi.com';
const ADMIN_PASSWORD = process.env.SEED_ADMIN_PASSWORD || 'admin123';
const SELLER_EMAIL = process.env.SEED_SELLER_EMAIL || 'seller@test.com';
const SELLER_PASSWORD = process.env.SEED_SELLER_PASSWORD || 'seller123';

const sampleCars = [
  {
    company: "Hindustan",
    model: "Ambassador Nova 1.5D",
    price: 185000,
    year: 1998,
    fuelType: "Diesel",
    transmission: "Manual",
    kmDriven: 142000,
    imageUrl: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800",
    description: "Classic ambassador in immaculate condition. Original engine, well-maintained body. Perfect for vintage enthusiasts.",
    bodyType: "Sedan",
    power: 56,
    torque: 122,
    zeroToSixty: 18.5,
    topSpeed: 120,
    range: 550,
    seats: 5,
    drivetrain: "RWD",
    colorName: "Cream White",
    colorHex: "#F5F5DC",
    ownerCount: 2,
    accidental: "Non-Accidental",
    insuranceStatus: "Valid Comprehensive",
    insuranceValid: true,
    features: ["Classic Bench Seats", "Power Steering Retrofit", "Original Dashboard", "Chrome Bumper"],
    registrationCity: "Delhi",
    sellerName: "Rajesh Kumar",
    sellerPhone: "9876543210",
    sellerCity: "Delhi",
    sellerEmail: "rajesh@test.com",
    status: "available"
  },
  {
    company: "Premier",
    model: "Padmini Delux",
    price: 120000,
    year: 1985,
    fuelType: "Petrol",
    transmission: "Manual",
    kmDriven: 85000,
    imageUrl: "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&q=80&w=800",
    description: "Charming vintage sedan in classic powder blue. Column shifter working perfectly. A rare piece of Indian motoring history.",
    bodyType: "Sedan",
    power: 42,
    torque: 71,
    zeroToSixty: 22.0,
    topSpeed: 110,
    range: 480,
    seats: 5,
    drivetrain: "RWD",
    colorName: "Powder Blue",
    colorHex: "#B0E0E6",
    ownerCount: 1,
    accidental: "Non-Accidental",
    insuranceStatus: "Expired",
    insuranceValid: false,
    features: ["Column Shifter", "Vent Windows", "Vintage Vinyl Seats", "Original Fiat Badging"],
    registrationCity: "Mumbai",
    sellerName: "Priya Sharma",
    sellerPhone: "9876543211",
    sellerCity: "Mumbai",
    sellerEmail: "priya@test.com",
    status: "available"
  },
  {
    company: "Hindustan",
    model: "Contessa Classic",
    price: 320000,
    year: 1990,
    fuelType: "Petrol",
    transmission: "Manual",
    kmDriven: 98000,
    imageUrl: "https://images.unsplash.com/photo-1542282088-fe8426682b8f?auto=format&fit=crop&q=80&w=800",
    description: "The muscle car of the East. Black gloss finish, custom interiors, smooth Isuzu engine. A head turner.",
    bodyType: "Sedan",
    power: 88,
    torque: 135,
    zeroToSixty: 12.8,
    topSpeed: 145,
    range: 520,
    seats: 5,
    drivetrain: "RWD",
    colorName: "Midnight Black",
    colorHex: "#111111",
    ownerCount: 2,
    accidental: "Minor Scratches",
    insuranceStatus: "Valid Comprehensive",
    insuranceValid: true,
    features: ["Power Windows", "Isuzu 1.8L Engine", "Custom Leather Seats", "Alloy Wheels"],
    registrationCity: "Pune",
    sellerName: "Amit Verma",
    sellerPhone: "9876543212",
    sellerCity: "Pune",
    sellerEmail: "amit@test.com",
    status: "sold"
  },
  {
    company: "Maruti Suzuki",
    model: "800 Standard",
    price: 65000,
    year: 1995,
    fuelType: "Petrol",
    transmission: "Manual",
    kmDriven: 72000,
    imageUrl: "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&q=80&w=800",
    description: "Single owner, original dashboard, great fuel economy. The car that put India on wheels.",
    bodyType: "Hatchback",
    power: 37,
    torque: 59,
    zeroToSixty: 19.2,
    topSpeed: 125,
    range: 450,
    seats: 4,
    drivetrain: "FWD",
    colorName: "Canary Red",
    colorHex: "#E63946",
    ownerCount: 1,
    accidental: "Non-Accidental",
    insuranceStatus: "Valid Comprehensive",
    insuranceValid: true,
    features: ["Compact Dimensions", "High Fuel Economy", "Original Japan Components"],
    registrationCity: "Bangalore",
    sellerName: "Suresh Patel",
    sellerPhone: "9876543213",
    sellerCity: "Bangalore",
    sellerEmail: "suresh@test.com",
    status: "available"
  },
  {
    company: "Standard",
    model: "Herald Saloon",
    price: 250000,
    year: 1968,
    fuelType: "Petrol",
    transmission: "Manual",
    kmDriven: 45000,
    imageUrl: "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&q=80&w=800",
    description: "Rare British lineage beauty. Cream white finish, authentic leather upholstery. Starts in a single crank.",
    bodyType: "Sedan",
    power: 39,
    torque: 68,
    zeroToSixty: 24.5,
    topSpeed: 105,
    range: 400,
    seats: 4,
    drivetrain: "RWD",
    colorName: "Ivory White",
    colorHex: "#FFFFF0",
    ownerCount: 3,
    accidental: "Non-Accidental",
    insuranceStatus: "Expired",
    insuranceValid: false,
    features: ["Forward Tilting Bonnet", "Wooden Steering Wheel", "Chrome Mirrors"],
    registrationCity: "Chennai",
    sellerName: "Vikram Singh",
    sellerPhone: "9876543214",
    sellerCity: "Chennai",
    sellerEmail: "vikram@test.com",
    status: "available"
  },
  {
    company: "Willys",
    model: "Jeep CJ-3B",
    price: 450000,
    year: 1962,
    fuelType: "Petrol",
    transmission: "Manual",
    kmDriven: 53000,
    imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&q=80&w=800",
    description: "Authentic 4x4 offroad pioneer. Olive green matte finish, transfer case works flawlessly.",
    bodyType: "SUV",
    power: 75,
    torque: 154,
    zeroToSixty: 16.0,
    topSpeed: 100,
    range: 380,
    seats: 4,
    drivetrain: "AWD",
    colorName: "Olive Green",
    colorHex: "#556B2F",
    ownerCount: 2,
    accidental: "Non-Accidental",
    insuranceStatus: "Third Party Only",
    insuranceValid: true,
    features: ["High-Low 4x4 Transfer Case", "Matte Military Finish", "Heavy Duty Tow Hook"],
    registrationCity: "Jaipur",
    sellerName: "Mohit Joshi",
    sellerPhone: "9876543215",
    sellerCity: "Jaipur",
    sellerEmail: "mohit@test.com",
    status: "available"
  },
  {
    company: "Mercedes-Benz",
    model: "240D W123",
    price: 680000,
    year: 1982,
    fuelType: "Diesel",
    transmission: "Automatic",
    kmDriven: 210000,
    imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=800",
    description: "German over-engineering at its finest. Coffee brown shade, pristine tan seats. Built to last.",
    bodyType: "Sedan",
    power: 72,
    torque: 137,
    zeroToSixty: 17.8,
    topSpeed: 138,
    range: 650,
    seats: 5,
    drivetrain: "RWD",
    colorName: "Coffee Brown",
    colorHex: "#4A2E12",
    ownerCount: 2,
    accidental: "Non-Accidental",
    insuranceStatus: "Valid Comprehensive",
    insuranceValid: true,
    features: ["Sunroof", "MB-Tex Leather", "Vacuum Power Locks", "Automatic Transmission"],
    registrationCity: "Delhi",
    sellerName: "Anil Mehta",
    sellerPhone: "9876543216",
    sellerCity: "Delhi",
    sellerEmail: "anil@test.com",
    status: "sold"
  },
  {
    company: "Toyota",
    model: "Land Cruiser FJ60",
    price: 950000,
    year: 1984,
    fuelType: "Petrol",
    transmission: "Manual",
    kmDriven: 185000,
    imageUrl: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=800",
    description: "Rugged overland explorer. High-roof styling, 4.2L inline 6. Mechanically sound, ready for cross-country runs.",
    bodyType: "SUV",
    power: 135,
    torque: 285,
    zeroToSixty: 13.5,
    topSpeed: 150,
    range: 580,
    seats: 7,
    drivetrain: "AWD",
    colorName: "Desert Bronze",
    colorHex: "#CD7F32",
    ownerCount: 1,
    accidental: "Non-Accidental",
    insuranceStatus: "Valid Comprehensive",
    insuranceValid: true,
    features: ["7-Seater Configuration", "4.2L 2F Engine", "All-Terrain Tyres", "Roof Rack"],
    registrationCity: "Hyderabad",
    sellerName: "Kiran Reddy",
    sellerPhone: "9876543217",
    sellerCity: "Hyderabad",
    sellerEmail: "kiran@test.com",
    status: "available"
  },
  {
    company: "BMW",
    model: "325i E30",
    price: 780000,
    year: 1988,
    fuelType: "Petrol",
    transmission: "Manual",
    kmDriven: 115000,
    imageUrl: "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&q=80&w=800",
    description: "Iconic coupe in crimson red. Smooth inline-6, BBS alloys, tight steering. A pure enthusiast's joy.",
    bodyType: "Coupe",
    power: 168,
    torque: 222,
    zeroToSixty: 8.3,
    topSpeed: 215,
    range: 540,
    seats: 4,
    drivetrain: "RWD",
    colorName: "Crimson Red",
    colorHex: "#DC143C",
    ownerCount: 2,
    accidental: "Non-Accidental",
    insuranceStatus: "Valid Comprehensive",
    insuranceValid: true,
    features: ["M-Tech Steering Wheel", "BBS Alloy Wheels", "Sport Suspension", "Sunroof"],
    registrationCity: "Mumbai",
    sellerName: "Neha Kapoor",
    sellerPhone: "9876543218",
    sellerCity: "Mumbai",
    sellerEmail: "neha@test.com",
    status: "available"
  },
  {
    company: "Volkswagen",
    model: "Beetle 1300",
    price: 520000,
    year: 1972,
    fuelType: "Petrol",
    transmission: "Manual",
    kmDriven: 89000,
    imageUrl: "https://images.unsplash.com/photo-1525609004556-c46c7d6cf0a3?auto=format&fit=crop&q=80&w=800",
    description: "Classic air-cooled bug in canary yellow. Immaculate chrome, original dials, signature boxer engine purr.",
    bodyType: "Hatchback",
    power: 44,
    torque: 86,
    zeroToSixty: 21.0,
    topSpeed: 125,
    range: 420,
    seats: 4,
    drivetrain: "RWD",
    colorName: "Canary Yellow",
    colorHex: "#FFEF00",
    ownerCount: 2,
    accidental: "Non-Accidental",
    insuranceStatus: "Expired",
    insuranceValid: false,
    features: ["Air-Cooled Boxer Engine", "Retro Dials", "Pop-out Rear Windows"],
    registrationCity: "Goa",
    sellerName: "Rahul D'Souza",
    sellerPhone: "9876543219",
    sellerCity: "Goa",
    sellerEmail: "rahul@test.com",
    status: "available"
  },
  {
    company: "Fiat",
    model: "1100 Millecento",
    price: 160000,
    year: 1964,
    fuelType: "Petrol",
    transmission: "Manual",
    kmDriven: 67000,
    imageUrl: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=800",
    description: "Pastel green round-body Fiat. Suicidal front doors, original steering wheel, retro chrome grille.",
    bodyType: "Sedan",
    power: 36,
    torque: 65,
    zeroToSixty: 25.0,
    topSpeed: 108,
    range: 390,
    seats: 4,
    drivetrain: "RWD",
    colorName: "Mint Green",
    colorHex: "#98FF98",
    ownerCount: 3,
    accidental: "Minor Scratches",
    insuranceStatus: "Valid Comprehensive",
    insuranceValid: true,
    features: ["Suicide Front Doors", "Chrome Ribbed Grille", "Classic White Wall Tyres"],
    registrationCity: "Kolkata",
    sellerName: "Arijit Sen",
    sellerPhone: "9876543220",
    sellerCity: "Kolkata",
    sellerEmail: "arijit@test.com",
    status: "available"
  },
  {
    company: "Hindustan",
    model: "Landmaster",
    price: 380000,
    year: 1956,
    fuelType: "Petrol",
    transmission: "Manual",
    kmDriven: 120000,
    imageUrl: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&q=80&w=800",
    description: "Predecessor to the Ambassador. Rare bubble boot design, original Smiths dials, vintage grey styling.",
    bodyType: "Sedan",
    power: 48,
    torque: 84,
    zeroToSixty: 23.0,
    topSpeed: 112,
    range: 410,
    seats: 5,
    drivetrain: "RWD",
    colorName: "Vintage Grey",
    colorHex: "#808080",
    ownerCount: 2,
    accidental: "Non-Accidental",
    insuranceStatus: "Expired",
    insuranceValid: false,
    features: ["Bubble Boot Styling", "Smiths Gauges", "Leatherette Interior"],
    registrationCity: "Ahmedabad",
    sellerName: "Ketan Patel",
    sellerPhone: "9876543221",
    sellerCity: "Ahmedabad",
    sellerEmail: "ketan@test.com",
    status: "available"
  }
];

const seedDatabase = async () => {
  try {
    await connectDB();
    await Car.deleteMany({});
    await Counter.deleteMany({});
    await User.deleteMany({});

    const admin = new User({ name: 'Admin', email: ADMIN_EMAIL, password: ADMIN_PASSWORD, role: 'admin', phone: '9000000000', city: 'Delhi' });
    await admin.save();
    console.log(`Admin: ${ADMIN_EMAIL}`);

    const seller = new User({ name: 'Test Seller', email: SELLER_EMAIL, password: SELLER_PASSWORD, role: 'seller', phone: '9111111111', city: 'Mumbai' });
    await seller.save();
    console.log(`Seller: ${SELLER_EMAIL}`);

    const counter = new Counter({ id: 'carLotNumber', seq: 0 });
    await counter.save();

    for (const carData of sampleCars) {
      const car = new Car(carData);
      const saved = await car.save();
      console.log(`Lot ${String(saved.lotNumber).padStart(3, '0')} - ${saved.company} ${saved.model}`);
    }
    console.log('Seed complete.');
    mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error('Seed failed:', error.message);
    mongoose.connection.close();
    process.exit(1);
  }
};
seedDatabase();
